name: Post Correct NRFI Predictions

on:
  schedule:
    # Run daily at 11am Eastern Time (15:00 UTC during EDT, 16:00 UTC during EST)
    - cron: '0 15 * * *'  # 11am EDT
  workflow_dispatch:  # Allow manual triggering

jobs:
  post_correct_predictions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy pandas python-dotenv

      - name: Run correct NRFI predictions script
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python correct_nrfis.py 